tap "gantoreno/macfetch"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "teamookla/speedtest"
brew "openjdk"
brew "ant"
brew "bat"
brew "bear"
brew "python@3.11"
brew "bpytop"
brew "fastfetch"
brew "fd"
brew "fzf"
brew "gcc"
brew "gdu"
brew "grip"
brew "lsd"
brew "mas"
brew "neovim"
brew "node"
brew "ranger"
brew "ripgrep"
brew "speedtest-cli"
brew "tmux"
brew "tree"
cask "aldente"
cask "amethyst"
cask "appcleaner"
cask "audacity"
cask "balenaetcher"
cask "bitwarden"
cask "gimp"
cask "hammerspoon"
cask "handbrake"
cask "hiddenbar"
cask "iina"
cask "keyclu"
cask "kitty"
cask "macdown"
cask "microsoft-auto-update"
cask "microsoft-teams"
cask "monitorcontrol"
cask "obsidian"
cask "orion"
cask "raycast"
cask "tomatobar"
cask "visual-studio-code"
mas "Color Picker", id: 1545870783
mas "DaVinci Resolve", id: 571213070
mas "Dropover", id: 1355679052
mas "Keynote", id: 409183694
mas "Noir", id: 1592917505
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Prime Video", id: 545519333
mas "Telegram", id: 747648890
mas "Vimari", id: 1480933944
vscode "Cardinal90.multi-cursor-case-preserve"
vscode "Catppuccin.catppuccin-vsc"
vscode "Catppuccin.catppuccin-vsc-icons"
vscode "ecmel.vscode-html-css"
vscode "formulahendry.vscode-mysql"
vscode "Gruntfuggly.todo-tree"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "ms-vscode.hexeditor"
vscode "ms-vsliveshare.vsliveshare"
vscode "ritwickdey.LiveServer"
vscode "tomoki1207.pdf"
vscode "vadimcn.vscode-lldb"
vscode "vintharas.learn-vim"
vscode "vscodevim.vim"
