after-login-command = []

after-startup-command = []

start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 12

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
default-root-container-orientation = 'auto'

# Possible values: (qwerty|dvorak)
key-mapping.preset = 'qwerty'

# mouse follows monitors and windows changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

# Gaps between windows (inner-*) and between monitor edges (outer-*).
[gaps]
inner.horizontal = 6
inner.vertical =   6
outer.left =       6
outer.bottom =     6
outer.top =        6
outer.right =      6

[mode.main.binding]
# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# change focused window
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# move windows
ctrl-alt-h = 'move left'
ctrl-alt-j = 'move down'
ctrl-alt-k = 'move up'
ctrl-alt-l = 'move right'


# change workspace
ctrl-1 = 'workspace 1'
ctrl-2 = 'workspace 2'
ctrl-3 = 'workspace 3'
ctrl-4 = 'workspace 4'
# ctrl-5 = 'workspace 5'
# ctrl-6 = 'workspace 6'
# ctrl-7 = 'workspace 7'
# ctrl-8 = 'workspace 8'
# ctrl-9 = 'workspace 9'
ctrl-t = 'workspace T'
ctrl-b = 'workspace B'

# move window to workspace
ctrl-alt-1 = 'move-node-to-workspace 1'
ctrl-alt-2 = 'move-node-to-workspace 2'
ctrl-alt-3 = 'move-node-to-workspace 3'
ctrl-alt-4 = 'move-node-to-workspace 4'
# ctrl-alt-5 = 'move-node-to-workspace 5'
# ctrl-alt-6 = 'move-node-to-workspace 6'
# ctrl-alt-7 = 'move-node-to-workspace 7'
# ctrl-alt-8 = 'move-node-to-workspace 8'
# ctrl-alt-9 = 'move-node-to-workspace 9'
ctrl-alt-t = 'move-node-to-workspace T'
ctrl-alt-b = 'move-node-to-workspace B'

ctrl-tab = 'workspace-back-and-forth' # Switch between workspaces

ctrl-alt-space = 'layout floating tiling' # Toggle between floating and tiling layout
ctrl-alt-f = 'fullscreen' # Toggle fullscreen

ctrl-alt-tab = 'move-workspace-to-monitor --wrap-around next' # Move workspace to next monitor

ctrl-alt-s = 'mode service' # Go in service mode
[mode.service.binding]
esc = 'mode main' # Exit service mode
c = ['reload-config', 'mode main'] # reload config
r = ['flatten-workspace-tree', 'mode main'] # reset layout
ctrl-backspace = ['close-all-windows-but-current', 'mode main'] # close all windows but current

# resize windows smartly
s = 'resize smart -50' # shrink
e = 'resize smart +50' # expand

# join windows into same container
ctrl-shift-h = 'join-with left'
ctrl-shift-j = 'join-with down'
ctrl-shift-k = 'join-with up'
ctrl-shift-l = 'join-with right'

# change layout
t = ['layout h_tiles v_tiles', 'mode main'] # toggle between tiles horizontal and vertical
a = ['layout h_accordion', 'mode main'] # switch to accordion horizontal

[[on-window-detected]]
if.app-id = 'org.alacritty'
run = 'move-node-to-workspace T' # mnemonics T - Terminal

[[on-window-detected]]
if.app-id = 'com.apple.Safari'
run = 'move-node-to-workspace B' # mnemonics W - Web browser

# auto float AppCleaner
[[on-window-detected]]
if.app-id = 'net.freemacsoft.AppCleaner'
run = 'layout floating' 

# auto float GIMP
[[on-window-detected]]
if.app-id = 'org.gimp.gimp-2.10'
run = 'layout floating'
