#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
bar=(
  height=32
  color=0x00000000
  shadow=off
  position=top
  padding_right=10
  padding_left=10
  topmost=window
)
sketchybar --bar "${bar[@]}"

default=(
  icon.font="Iosevka Nerd Font Propo:Bold:17.0"
  label.font="Iosevka Nerd Font Propo:Bold:14.0"
  # background.color=0xff161616
  # background.corner_radius=12
  padding_left=5
  padding_right=5
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"


sketchybar --add event aerospace_workspace_change

for sid in $(aerospace list-workspaces --all); do
    sketchybar --add item space.$sid left \
        --subscribe space.$sid aerospace_workspace_change \
        --set space.$sid \
        background.color=0x44ffffff \
        background.corner_radius=5 \
        background.height=20 \
        background.drawing=off \
        label="$sid" \
        click_script="aerospace workspace $sid" \
        script="$CONFIG_DIR/plugins/aerospace.sh $sid"
done

##### Left Side Items #####
sketchybar --add item chevron left \
           --set chevron icon= label.drawing=off \
           --add item front_app left \
           --set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh" \
           --subscribe front_app front_app_switched

##### Right Side Items #####
source "$ITEM_DIR/calendar.sh"

# reload sketchybar on save
sketchybar --hotload on

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
