#!/bin/sh

source "$CONFIG_DIR/colors.sh" 
PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEMS_DIR="$CONFIG_DIR/items"

FONT="Iosevka Nerd Font" 
PADDINGS=8

##### Bar Appearance #####

sketchybar --bar     height=32                                         \
                     color=$TRANSPARENT                                  \
                     position=top                                      \
                     sticky=on                                         \
                     corner_radius=12                                  \
                     padding_left=0                                   \
                     padding_right=0                                   \
                     y_offset=3                                        \
                     margin=6                                          \
                     blur_radius=33                                    \
                                                                       \
           --default updates=when_shown                                \
                     icon.font="$FONT:Regular:14.0"                    \
                     icon.color=$WHITE                            \
                     icon.padding_left=$PADDINGS                       \
                     icon.padding_right=$PADDINGS                      \
                     label.font="$FONT:Regular:14.0"                   \
                     label.color=$WHITE                          \
                     label.padding_left=$PADDINGS                      \
                     label.padding_right=$PADDINGS                     \
                     background.height=26                              \
                     background.color=$BLACK                           \
                     background.border_width=1                         \
                     background.border_color=$BORDER                   \
                     background.padding_right=4                \
                     background.padding_left=4                 \
                     background.corner_radius=12                        \
                     background.blur_radius=33                         \
                     popup.background.drawing=on \
                     popup.background.color=$GREY \
                     popup.background.border_color=$BORDER \
                     popup.background.border_width=1 \
                     popup.background.corner_radius=8 \
                     popup.background.padding_left=4 \
                     popup.background.padding_right=4 \
                     popup.blur_radius=33 \
                     popup.align=center \

##### Left Items #####

# Spaces
source "$ITEMS_DIR/aerospace.sh"

# Front App
source "$ITEMS_DIR/front_app.sh"

##### Right Items #####

# Calendar
source "$ITEMS_DIR/calendar.sh"

# Battery
source "$ITEMS_DIR/wifi.sh"

# WiFi
source "$ITEMS_DIR/battery.sh"
sketchybar --add bracket stats wifi battery \
           --set stats \

# sketchybar --hotload on
sketchybar --update
