#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source "$CONFIG_DIR/icons.sh" # Loads all defined icons

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

FONT="Iosevka Nerd Font Propo"

##### Bar Appearance #####
bar=(
  height=32
  color=$TRANSPARENT
  shadow=off
  position=top
  padding_right=10
  padding_left=10
)
sketchybar --bar "${bar[@]}"

default=(
  icon.font="$FONT:Bold:17.0"
  label.font="$FONT:Bold:14.0"
  background.color=$BACKGROUND
  background.corner_radius=12
  background.border_width=2
  background.border_color=$BORDER
  padding_left=4
  padding_right=4
  icon.color=$FOREGROUND
  label.color=$FOREGROUND
  icon.padding_left=10
  icon.padding_right=10
  label.padding_left=10
  label.padding_right=10
)
sketchybar --default "${default[@]}"

##### Left Side Items #####
source "$ITEM_DIR/aerospace.sh"
source "$ITEM_DIR/front_app.sh"

##### Right Side Items #####
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/battery.sh"

# reload sketchybar on save
sketchybar --hotload on

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
