# colors
import = [
  "~/.config/alacritty/catppuccin-mocha.toml",
]

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 100

[env]
TERM = "xterm-256color"

[font]
normal.family = "MesloLGS NF"
size = 16

[[keyboard.bindings]]
chars = """
clear
"""
key = "K"
mods = "Command"

[mouse]
hide_when_typing = false

[scrolling]
history = 100000
multiplier = 1

[selection]
save_to_clipboard = true

[window]
decorations = "buttonless"
opacity = 0.8
blur = true
startup_mode = "Maximized"
dynamic_padding = true

[window.padding]
x = 4
y = 2

[window.position]
x = 0
y = 0
